export const GET_IMAGES_STARTED = 'GET_IMAGES_STARTED'
export const GET_IMAGES_SUCCESS = 'GET_IMAGES_SUCCESS'
export const GET_IMAGES_FAILURE = 'GET_IMAGES_FAILURE'
export const GET_IMAGES_ENDED = 'GET_IMAGES_ENDED'